/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedRbacRouteImport } from './routes/_authenticated/rbac'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedRbacRolesRouteImport } from './routes/_authenticated/rbac/roles'
import { Route as AuthenticatedRbacRolesIndexRouteImport } from './routes/_authenticated/rbac/roles.index'
import { Route as AuthenticatedRbacRolesRoleIdRouteImport } from './routes/_authenticated/rbac/roles.$roleId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRbacRoute = AuthenticatedRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedRbacRolesRoute = AuthenticatedRbacRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRbacRoute,
} as any)
const AuthenticatedRbacRolesIndexRoute =
  AuthenticatedRbacRolesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRbacRolesRoute,
  } as any)
const AuthenticatedRbacRolesRoleIdRoute =
  AuthenticatedRbacRolesRoleIdRouteImport.update({
    id: '/$roleId',
    path: '/$roleId',
    getParentRoute: () => AuthenticatedRbacRolesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rbac': typeof AuthenticatedRbacRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/rbac/roles': typeof AuthenticatedRbacRolesRouteWithChildren
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/rbac/roles/$roleId': typeof AuthenticatedRbacRolesRoleIdRoute
  '/rbac/roles/': typeof AuthenticatedRbacRolesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rbac': typeof AuthenticatedRbacRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/rbac/roles/$roleId': typeof AuthenticatedRbacRolesRoleIdRoute
  '/rbac/roles': typeof AuthenticatedRbacRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rbac': typeof AuthenticatedRbacRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/rbac/roles': typeof AuthenticatedRbacRolesRouteWithChildren
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/rbac/roles/$roleId': typeof AuthenticatedRbacRolesRoleIdRoute
  '/_authenticated/rbac/roles/': typeof AuthenticatedRbacRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/rbac'
    | '/users'
    | '/rbac/roles'
    | '/users/'
    | '/rbac/roles/$roleId'
    | '/rbac/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile'
    | '/rbac'
    | '/'
    | '/users'
    | '/rbac/roles/$roleId'
    | '/rbac/roles'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/profile'
    | '/_authenticated/rbac'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/rbac/roles'
    | '/_authenticated/users/'
    | '/_authenticated/rbac/roles/$roleId'
    | '/_authenticated/rbac/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rbac': {
      id: '/_authenticated/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof AuthenticatedRbacRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/rbac/roles': {
      id: '/_authenticated/rbac/roles'
      path: '/roles'
      fullPath: '/rbac/roles'
      preLoaderRoute: typeof AuthenticatedRbacRolesRouteImport
      parentRoute: typeof AuthenticatedRbacRoute
    }
    '/_authenticated/rbac/roles/': {
      id: '/_authenticated/rbac/roles/'
      path: '/'
      fullPath: '/rbac/roles/'
      preLoaderRoute: typeof AuthenticatedRbacRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRbacRolesRoute
    }
    '/_authenticated/rbac/roles/$roleId': {
      id: '/_authenticated/rbac/roles/$roleId'
      path: '/$roleId'
      fullPath: '/rbac/roles/$roleId'
      preLoaderRoute: typeof AuthenticatedRbacRolesRoleIdRouteImport
      parentRoute: typeof AuthenticatedRbacRolesRoute
    }
  }
}

interface AuthenticatedRbacRolesRouteChildren {
  AuthenticatedRbacRolesRoleIdRoute: typeof AuthenticatedRbacRolesRoleIdRoute
  AuthenticatedRbacRolesIndexRoute: typeof AuthenticatedRbacRolesIndexRoute
}

const AuthenticatedRbacRolesRouteChildren: AuthenticatedRbacRolesRouteChildren =
  {
    AuthenticatedRbacRolesRoleIdRoute: AuthenticatedRbacRolesRoleIdRoute,
    AuthenticatedRbacRolesIndexRoute: AuthenticatedRbacRolesIndexRoute,
  }

const AuthenticatedRbacRolesRouteWithChildren =
  AuthenticatedRbacRolesRoute._addFileChildren(
    AuthenticatedRbacRolesRouteChildren,
  )

interface AuthenticatedRbacRouteChildren {
  AuthenticatedRbacRolesRoute: typeof AuthenticatedRbacRolesRouteWithChildren
}

const AuthenticatedRbacRouteChildren: AuthenticatedRbacRouteChildren = {
  AuthenticatedRbacRolesRoute: AuthenticatedRbacRolesRouteWithChildren,
}

const AuthenticatedRbacRouteWithChildren =
  AuthenticatedRbacRoute._addFileChildren(AuthenticatedRbacRouteChildren)

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRbacRoute: typeof AuthenticatedRbacRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRbacRoute: AuthenticatedRbacRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
